Repository openshift/imagebuilder, pull requests merged in 2018-10, with the labels that each got.

#106 Add basic OWNERS file for now
  OWNERS
Labels: approved, lgtm

#105 Remove some dead code and simplifications
  dispatchers.go
  dockerclient/copyinfo.go
  dockerclient/directory.go
  evaluator.go
  imageprogress/progress.go
  imageprogress/progress_test.go
Labels: approved, lgtm, size/S

#104 Add support for heading ARG in Dockerfile
  builder.go
  builder_test.go
  cmd/imagebuilder/imagebuilder.go
  dispatchers.go
  dockerclient/conformance_test.go
  dockerclient/testdata/multistage/Dockerfile.heading-arg
Labels: approved, lgtm, size/L
