Repository openshift/imagebuilder, pull requests merged in 2019-07, with the labels that each got.

#130 Migrate from glog to klog
  cmd/imagebuilder/imagebuilder.go
  dockerclient/archive.go
  dockerclient/client.go
  dockerclient/directory.go
  vendor.conf
  vendor/github.com/gogo/protobuf/go.mod
  vendor/github.com/golang/glog/README
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, lgtm, size/L

#131 README: Add podman specific note
  README.md
Labels: approved, lgtm, size/XS

#132 remove bparees from reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#133 Bug 1730446: dockerclient newArchiveMapper: always end archiveRoot with "/"
  dockerclient/archive.go
  dockerclient/archive_test.go
  dockerclient/conformance_test.go
  dockerclient/testdata/Dockerfile.copyfrom_11
  dockerclient/testdata/Dockerfile.copyfrom_12
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#129 Use imported constants instead of our own
  constants.go
  evaluator.go
Labels: approved, lgtm, size/S
