Repository openshift/imagebuilder, pull requests merged in 2019-02, with the labels that each got.

#121 Add ThroughTarget function to builder
  builder.go
  builder_test.go
  dockerclient/testdata/Dockerfile.target
Labels: approved, lgtm, size/M

#120 Make readme less Docker centric and add VERSION
  README.md
Labels: approved, lgtm, size/S

#123 Make the comment in docker history slightly more readable
  dockerclient/client.go
Labels: approved, lgtm, size/XS
