Repository openshift/imagebuilder, pull requests merged in 2019-01, with the labels that each got.

#115 Create version 1.0 of imagebuilder
  cmd/imagebuilder/imagebuilder.go
  imagebuilder.spec
Labels: approved, lgtm, size/S

#113 issue 87: ensure WORKDIR exists
  builder.go
  builder_test.go
  dockerclient/client.go
  dockerclient/conformance_test.go
  dockerclient/testdata/Dockerfile.novolume
  dockerclient/testdata/Dockerfile.novolumenorun
Labels: approved, lgtm, size/L

#50 Handle VOLUME statements referring to missing dirs
  dockerclient/conformance_test.go
  dockerclient/testdata/Dockerfile.volumeexists
Labels: approved, lgtm, size/XS

#119 ADD supports the chown option also
  dispatchers.go
  dispatchers_test.go
Labels: approved, lgtm, size/M
