Repository openshift/imagebuilder, pull requests merged in 2020-03, with the labels that each got.

#147 NewBuilder(): always initialize Args
  builder.go
Labels: approved, lgtm, size/XS

#148 dockerclient: detect ENOENT when copying
  dockerclient/archive.go
  dockerclient/archive_112.go
  dockerclient/archive_113.go
  dockerclient/archive_test.go
  dockerclient/client.go
Labels: approved, lgtm, size/L

#149 Process env substiturion in ADD, COPY commands
  dispatchers.go
Labels: approved, lgtm, size/S

#150 Add tests to verify copy and add with environment substitution.
  dispatchers.go
  dispatchers_test.go
Labels: approved, lgtm, size/L

#101 Copy .dockerignore into image for compatibility with Docker
  dockerclient/client.go
Labels: approved, lgtm, size/XS

#152 Fix error output in archive.go
  dockerclient/archive.go
Labels: approved, lgtm

#153 archiveFromContainer(): return possibly-wrapped os.IsNotError
  dockerclient/archive.go
Labels: approved

#151 Treat args the same way `docker build` does
  builder.go
  builder_test.go
  dispatchers.go
  dockerclient/testdata/multistage/Dockerfile.arg-scope
  dockerclient/testdata/multistage/Dockerfile.heading-arg
  dockerclient/testdata/multistage/Dockerfile.heading-redefine
Labels: approved, lgtm, ok-to-test, size/M
