Repository openshift/imagebuilder, pull requests merged in 2023-05, with the labels that each got.

#253 chore(docs): 2 small updates to README
  README.md
Labels: lgtm, approved, ok-to-test

#255 Tag v1.2.5
  cmd/imagebuilder/imagebuilder.go
  imagebuilder.spec
Labels: approved

#256 RUN-1833: dockerclient: use /bin/sleep for idling instead of sleep
  dockerclient/client.go
Labels: lgtm, approved, jira/valid-reference
